src/Entity/Reservations.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\ReservationsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationsRepository::class)]
#[ApiResource()]
class Reservations
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'date')]
    private $arrival_date;

    #[ORM\Column(type: 'date')]
    private $departure_date;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'reservations')]
    private $user;

    #[ORM\ManyToOne(targetEntity: Establishments::class, inversedBy: 'reservations')]
    private $establishment;

    #[ORM\ManyToOne(targetEntity: Suites::class, inversedBy: 'reservations')]
    private $suite;



    public function __construct()
    {
        $this->establishment = new ArrayCollection();
        $this->suite = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getArrivalDate(): ?\DateTimeInterface
    {
        return $this->arrival_date;
    }

    public function setArrivalDate(\DateTimeInterface $arrival_date): self
    {
        $this->arrival_date = $arrival_date;

        return $this;
    }

    public function getDepartureDate(): ?\DateTimeInterface
    {
        return $this->departure_date;
    }

    public function setDepartureDate(\DateTimeInterface $departure_date): self
    {
        $this->departure_date = $departure_date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getEstablishment(): ?Establishments
    {
        return $this->establishment;
    }

    public function setEstablishment(?Establishments $establishment): self
    {
        $this->establishment = $establishment;

        return $this;
    }

    public function getSuite(): ?Suites
    {
        return $this->suite;
    }

    public function setSuite(?Suites $suite): self
    {
        $this->suite = $suite;

        return $this;
    }



}

src/Entity/Suites.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;
use App\Repository\SuitesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


#[ORM\Entity(repositoryClass: SuitesRepository::class)]
#[ApiResource]
#[ApiFilter(SearchFilter::class, properties: ['establishment.id' => 'exact'])]

class Suites
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;


    #[ORM\Column(type: 'string', length: 255)]
    private $description;

    #[ORM\Column(type: 'decimal', precision: 5, scale: 2)]
    private $price;

    #[ORM\Column(type: 'string', length: 255)]
    private $picture;


    #[ORM\ManyToOne(targetEntity: Establishments::class, inversedBy: 'suites')]
    private $establishment;


    #[ORM\OneToMany(mappedBy: 'suite', targetEntity: ImagesSuites::class, cascade: ['persist'])]
    private $images;

    #[ORM\OneToMany(mappedBy: 'suite', targetEntity: Reservations::class)]
    private $reservations;


    public function __construct()
    {

        $this->images = new ArrayCollection();
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }



    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }



    public function getEstablishment(): ?Establishments
    {
        return $this->establishment;
    }

    public function setEstablishment(?Establishments $establishment): self
    {
        $this->establishment = $establishment;

        return $this;
    }



    /**
     * @return Collection<int, ImagesSuites>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function getMainImage() {
        return $this->images->get(array_rand($this->images->toArray()));
    }

    public function addImage(ImagesSuites $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setSuite($this);
        }

        return $this;
    }

    public function removeImage(ImagesSuites $image): self
    {
        if ($this->image->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getSuite() === $this) {
                $image->setSuite(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Reservations>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservations $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setSuite($this);
        }

        return $this;
    }

    public function removeReservation(Reservations $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getSuite() === $this) {
                $reservation->setSuite(null);
            }
        }

        return $this;
    }
}

src/Form/ReservationsType.php
<?php

namespace App\Form;

use App\Entity\Establishments;
use App\Entity\Reservations;
use App\Entity\Suites;
use App\Entity\User;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Security;

class ReservationsType extends AbstractType
{


    public function buildForm(FormBuilderInterface $builder, array $options): void
    {


        $builder
            ->add('arrival_date', DateType::class, [
                'required' => true])
            ->add('departure_date', DateType::class, [
                'required' => true])

            ->add('establishment', EntityType::class, [
                'class' => Establishments::class,
                'choice_label' => function (Establishments $establishments) {
                    return $establishments->getName();
                },
                'required' => true
            ])
            ->add('suite', EntityType::class, [
                'class' => Suites::class,
                'choice_label' => 'title',
                'required' => true
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservations::class,
        ]);
    }
}

src/Controller/ReservationsController.php
<?php

namespace App\Controller;

use App\Entity\Reservations;
use App\Form\ReservationsType;
use App\Repository\ReservationsRepository;
use App\Validator\ReservationDelete;
use App\Validator\ReservationDeleteValidator;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpFoundation\Session\SessionBagInterface;
use Symfony\Component\Routing\Annotation\Route;


class ReservationsController extends AbstractController
{
    #[Route('/reservations', name: 'reservations_list', methods: ['GET'])]
    public function index(ReservationsRepository $reservationsRepository, Session $session): Response
    {
        return $this->render('reservations/index.html.twig', [
            'reservations' => $reservationsRepository->findAll(),
        ]);
    }

    #[Route('/reservations/new', name: 'reservations_list_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ReservationsRepository $reservationsRepository): Response
    {
        $reservation = new Reservations();
        $form = $this->createForm(ReservationsType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservationsRepository->add($reservation);
            return $this->redirectToRoute('reservations_list', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservations/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/reservations/{id}', name: 'reservations_list_show', methods: ['GET'])]
    public function show(Reservations $reservation): Response
    {
        return $this->render('reservations/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    #[Route('/reservations/{id}/edit', name: 'reservations_list_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reservations $reservation, ReservationsRepository $reservationsRepository): Response
    {
        $form = $this->createForm(ReservationsType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservationsRepository->add($reservation);
            return $this->redirectToRoute('reservations_list', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservations/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/reservations/{id}', name: 'reservations_list_delete', methods: ['POST'])]
    public function delete(Request $request, Reservations $reservation, ReservationsRepository $reservationsRepository, ReservationDeleteValidator $validator): Response
    {
        if ($this->isCsrfTokenValid('delete' . $reservation->getId(), $request->request->get('_token'))) {

            if (!$validator->validate($reservation, new ReservationDelete())) {
                $referer = $request->headers->get('referer');
                return $this->redirect($referer);
            }

            $reservationsRepository->remove($reservation);
        }

        return $this->redirectToRoute('Home', [], Response::HTTP_SEE_OTHER);
    }


}

templates/reservations/Ajax.html.twig
{% block body %}



    <!-- Booking Start -->
    {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}

        <div class="container-fluid booking pb-5">
            <div class="container">
                <div class="bg-white shadow" style="padding: 35px;">
                    <h2 class="text-center">Verifiez les disponibilités de nos suites</h2>
                    <div class="row g-2">
                        <div class="col-md-10">
                            <div class="row g-2">
                                <div class="col-md-4">
                                    <div class="date" id="date1" data-target-input="nearest">
                                        <input id="arrival_date"
                                               type="date" class="form-control datetimepicker-input"
                                               min="{{ "now"|date("Y-m-d") }}"
                                               placeholder="Date d'arrivée" data-target="#date1"
                                               data-toggle="datetimepicker"
                                               name="arrival_date"/>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="date" id="date2" data-target-input="nearest">
                                        <input
                                                id="departure_date"
                                                type="date" class="form-control datetimepicker-input"
                                                min="{{ "now"|date("Y-m-d") }}"
                                                placeholder="Date de départ" data-target="#date2"
                                                data-toggle="datetimepicker"
                                                name="departure_date"/>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <select class="form-select" name="establishment" id="establishment">
                                        <option selected disabled>Etablissement</option>
                                        {% for establishment in establishments %}
                                            <option value="{{ establishment.id }}" {{ loop.first ? 'selected' : '' }}>
                                                {{ establishment.name }}
                                            </option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2 text-center">
                            <div id="loader" class="spinner-border text-dark" role="status" style="display: none;">
                                <span class="visually-hidden">Chargement en cours...</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="section-title text-center text-primary text-uppercase"><a href="{{ path('app_register') }}">Pas de compte? Incrivez-vous pour vérifier la disponibilité de nos suites</a></div>
    {% endif %}

    <!-- Booking End -->


    <div id="thubmnails"></div>


{% endblock %}

{% block script %}
    <script>
        let arrivalDateValue = null;
        let departureDateValue = null;
        let establishmentValue = null;


        $(document).ready(() => {
            onArrivalDateChange();
            onDepartureDateChange();
            onEstablishmentChange();
        })

        $("#arrival_date").change(onArrivalDateChange);
        $("#departure_date").change(onDepartureDateChange);
        $("#establishment").change(onEstablishmentChange);

        function onArrivalDateChange() {
            arrivalDateValue = $("#arrival_date").val();
            fetchSuites();
        }

        function onDepartureDateChange() {
            departureDateValue = $("#departure_date").val();
            fetchSuites();
        }

        function onEstablishmentChange() {
            establishmentValue = $("#establishment").val();
            fetchSuites();
        }

        function filterSuites(suites = []) {
            return suites.filter(({reservations = []}) => {
                if (reservations.length === 0) return true;
                let valid = true;
                reservations.forEach(({arrival_date, departure_date}) => {
                    console.log({arrival_date, departure_date, departureDateValue, arrivalDateValue});

                    // Si la date de debut de resa est dans l'interval
                    if (arrival_date >= arrivalDateValue && arrival_date <= departureDateValue) {
                        valid = false;
                    }

                    // si la date de fin de resa est dans l'interval
                    if (departure_date >= arrivalDateValue && departure_date <= departureDateValue) {
                        valid = false;
                    }

                    // si les dates de la resa englobe l'interval
                    if (arrival_date <= arrivalDateValue && departure_date >= departureDateValue) {
                        valid = false;
                    }
                });
                return valid;
            })
        }

        function fetchSuites() {
            if (arrivalDateValue && departureDateValue && establishmentValue) {
                // do ajax call
                $("#loader").show();
                $.get("/api/suites", {'establishment.id': establishmentValue})
                    .done((data) => {
                        const suites = data['hydra:member'];
                        const reservableSuites = filterSuites(suites);

                        $("#thubmnails").html('');
                        $("#loader").hide();

                        reservableSuites.forEach((suite) => {
                            generateThumbnailHTML(suite);
                        });
                    })
                    .fail((err) => {
                        console.log(err);
                        $("#loader").hide();
                    });
            }
        }


        function generateThumbnailHTML(suite) {
            $("#loader").show();
            const uri = "{{ absolute_url(path('thumbnail', {'id': '_id_'})) }}".replace('_id_', suite.id);

            const url = new URL(uri);
            url.searchParams.append('arrival_date', arrivalDateValue);
            url.searchParams.append('departure_date', departureDateValue);

            $.get(url).done((html) => {
                $("#thubmnails").append(html);
                $("#loader").hide();
            }).fail((err) => {
                console.log('err');
                $("#loader").hide();
            });
        }


    </script>
{% endblock %}

templates/reservations/_delete_form.html.twig
<form method="post" action="{{ path('reservations_list_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Etes-vous sur de vouloir supprimer?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button type="submit" class="btn btn-sm btn-primary rounded py-2 px-4">Supprimer</button>
</form>

templates/reservations/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary w-100 py-3">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/reservations/booking.html.twig
{% extends 'base.html.twig' %}

{% block title %} Réservations {% endblock %}

{% block body %}

    <!-- Booking Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="text-center">
                <h6 class="section-title text-center text-primary text-uppercase">Regarder nos établissements</h6>
                <h1 class="mb-5">Réservez une <span class="text-primary text-uppercase">Luxieuse suite</span></h1>
            </div>

            {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
                {{ include('reservations/_form.html.twig') }}
            {% else %}
                <div class="section-title text-center text-primary text-uppercase"><a href="{{ path('app_register') }}">Pas de compte? Incrivez-vous</a></div>
            {% endif %}


        </div>
    </div>
    <!-- Booking End -->



{% endblock %}

{% block script %}
    <script>




    </script>


{% endblock %}

templates/reservations/bookingShowCustomer.html.twig
{% extends 'base.html.twig' %}

{% block title %} Mes réservations {% endblock %}

{% block body %}
    {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
        <h1>Mes réservations</h1>

        <table class="table">
            <thead>
            <tr>
                <th>Id</th>
                <th>Etablissement</th>
                <th>Suite</th>
                <th>Date d'arrivée</th>
                <th>Date de départ</th>
                <th>Annuler</th>
            </tr>
            </thead>
            <tbody>
            {% for reservation in reservations %}
                <tr>
                    <td> {{ reservation.id }}</td>
                    <td>
                         {{ reservation.establishment.name }}
                    </td>
                    <td>
                        {{ reservation.suite.title }}
                    </td>
                    <td>{{ reservation.arrivalDate ? reservation.arrivalDate|date('Y-m-d') : '' }}</td>
                    <td>{{ reservation.departureDate ? reservation.departureDate|date('Y-m-d') : '' }}</td>
                    <td>
                        {{ include('reservations/_delete_form.html.twig') }}

                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="4">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="section-title text-center text-primary text-uppercase"><a href="{{ path('app_register') }}">Pas de
                compte? Incrivez-vous</a></div>
    {% endif %}

{% endblock %}

templates/reservations/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reservations{% endblock %}

{% block main %}
    <h1>Edit Reservations</h1>

    {{ include('reservations/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('reservations_list') }}">back to list</a>

    {{ include('reservations/_delete_form.html.twig') }}
{% endblock %}

templates/reservations/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservations index{% endblock %}

{% block body %}
    <h1>Reservations index</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Arrival_date</th>
            <th>Departure_date</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
            <tr>
                <td>{{ reservation.id }}</td>
                <td>{{ reservation.arrivalDate ? reservation.arrivalDate|date('Y-m-d') : '' }}</td>
                <td>{{ reservation.departureDate ? reservation.departureDate|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('reservations_list_show', {'id': reservation.id}) }}">show</a>
                    <a href="{{ path('reservations_list_edit', {'id': reservation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('reservations_list_new') }}">Create new</a>
{% endblock %}

templates/reservations/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reservations{% endblock %}

{% block main %}
    <h1>Create new Reservations</h1>

    {{ include('reservations/_form.html.twig') }}

    <a href="{{ path('reservations_list') }}">back to list</a>
{% endblock %}

templates/reservations/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservations{% endblock %}

{% block main %}
    <h1>Reservations</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ reservation.id }}</td>
        </tr>
        <tr>
            <th>Arrival_date</th>
            <td>{{ reservation.arrivalDate ? reservation.arrivalDate|date('Y-m-d') : '' }}</td>
        </tr>
        <tr>
            <th>Departure_date</th>
            <td>{{ reservation.departureDate ? reservation.departureDate|date('Y-m-d') : '' }}</td>
        </tr>
        </tbody>
    </table>

    <a href="{{ path('reservations_list') }}">back to list</a>

    <a href="{{ path('reservations_list_edit', {'id': reservation.id}) }}">edit</a>

    {{ include('reservations/_delete_form.html.twig') }}
{% endblock %}

templates/reservations/thumbnail.html.twig
{%  block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/style.css')}}">
    <link rel="stylesheet" href={{ asset('css/bootstrap.min.css') }} >
{% endblock %}


<div class="container-xxl py-5">
    <div class="container">

        <div class="row g-4">
            <div class="col-lg-12 col-md-10">
                <div class="room-item shadow rounded overflow-hidden">
                    <div class="position-relative">
                        <img class="w-100"  src={{ asset(suite.mainImage) }} alt="Image">
                        <small class=" start-0 top-100 translate-middle-y bg-primary text-white rounded py-1 px-3 ms-4">120€/nuit</small>
                    </div>
                    <div class="p-4 mt-2">
                        <div class="d-flex justify-content-between mb-3">
                            <h5 class="mb-0">{{ suite.title }}</h5>
                            <div class="ps-2">
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                            </div>
                        </div>
                        <div class="d-flex mb-3">
                            <small class="border-end me-3 pe-3"><i class="fa fa-hotel text-primary me-2"></i>Disponibles</small>
                            <small class="border-end me-3 pe-3"><i class="fa fa-spa text-primary me-2"></i>Spa</small>
                            <small><i class="fa fa-wifi text-primary me-2"></i>Wifi</small>
                        </div>
                        <p class="text-body mb-3">{{ suite.description }}</p>
                        <div class="d-flex justify-content-between">
                            <a class="btn btn-sm btn-primary rounded py-2 px-4" href="{{ path('suites_show', {'id': suite.id}) }}">Plus de détails</a>
                            <a class="btn btn-sm btn-dark rounded py-2 px-4" href={{ bookingUrl }}>Réserver maintenant</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>